version: '3'

services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=neeraj@0102
    redis:
        image: 'redis:latest'
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        stdin_open: true
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=root
            - PGHOST=localhost
            - PGDATABASE=root
            - PGPASSWORD=neeraj@0102
            - PGPORT=5432
        depends_on: 
            - postgres
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
                - /app/node_modules
                - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on: 
            - api
            - client